<?xml version="1.0" encoding="utf-8"?>
<Database Name="BLOOMDataBase" Class="BookLinqConnecionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=BLOOMDataBase;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BLOOMDataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.book_BookInfo" Member="book_BookInfo">
    <Type Name="book_BookInfo">
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PublicationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Extract" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserScored" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalScore" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Pages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Snapshot" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ViewedTimes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BoughtTimes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="book_BookInfo_book_BookBought" Member="book_BookBought" ThisKey="BookId" OtherKey="BookId" Type="book_BookBought" />
      <Association Name="book_BookInfo_book_BooksBelong" Member="book_BooksBelong" ThisKey="BookId" OtherKey="BookId" Type="book_BooksBelong" />
      <Association Name="book_BookInfo_book_Bookmarks" Member="book_Bookmarks" ThisKey="BookId" OtherKey="BookId" Type="book_Bookmarks" />
      <Association Name="book_BookInfo_book_Remarks" Member="book_Remarks" ThisKey="BookId" OtherKey="BookId" Type="book_Remarks" />
      <Association Name="book_BookInfo_book_BooksViewed" Member="book_BooksViewed" ThisKey="BookId" OtherKey="BookId" Type="book_BooksViewed" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_Users">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Users_book_BookBought" Member="book_BookBought" ThisKey="UserId" OtherKey="UserId" Type="book_BookBought" />
      <Association Name="aspnet_Users_book_Bookmarks" Member="book_Bookmarks" ThisKey="UserId" OtherKey="UserId" Type="book_Bookmarks" />
      <Association Name="aspnet_Users_book_Remarks" Member="book_Remarks" ThisKey="UserId" OtherKey="UserId" Type="book_Remarks" />
      <Association Name="aspnet_Users_book_BooksViewed" Member="book_BooksViewed" ThisKey="UserId" OtherKey="UserId" Type="book_BooksViewed" />
    </Type>
  </Table>
  <Table Name="dbo.book_BookBought" Member="book_BookBought">
    <Type Name="book_BookBought">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoneyPaid" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="aspnet_Users_book_BookBought" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
      <Association Name="book_BookInfo_book_BookBought" Member="book_BookInfo" ThisKey="BookId" OtherKey="BookId" Type="book_BookInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.book_BooksBelong" Member="book_BooksBelong">
    <Type Name="book_BooksBelong">
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BooksBelongId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="book_BookInfo_book_BooksBelong" Member="book_BookInfo" ThisKey="BookId" OtherKey="BookId" Type="book_BookInfo" IsForeignKey="true" />
      <Association Name="book_Categories_book_BooksBelong" Member="book_Categories" ThisKey="CategoryId" OtherKey="CategoryId" Type="book_Categories" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.book_Bookmarks" Member="book_Bookmarks">
    <Type Name="book_Bookmarks">
      <Column Name="BookmarkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="BookId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookmarkPage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="aspnet_Users_book_Bookmarks" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
      <Association Name="book_BookInfo_book_Bookmarks" Member="book_BookInfo" ThisKey="BookId" OtherKey="BookId" Type="book_BookInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.book_Categories" Member="book_Categories">
    <Type Name="book_Categories">
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="book_Categories_book_BooksBelong" Member="book_BooksBelong" ThisKey="CategoryId" OtherKey="CategoryId" Type="book_BooksBelong" />
    </Type>
  </Table>
  <Table Name="dbo.book_Remarks" Member="book_Remarks">
    <Type Name="book_Remarks">
      <Column Name="RemarkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="BookId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RemarkDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="book_BookInfo_book_Remarks" Member="book_BookInfo" ThisKey="BookId" OtherKey="BookId" Type="book_BookInfo" IsForeignKey="true" />
      <Association Name="aspnet_Users_book_Remarks" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.book_BooksViewed" Member="book_BooksViewed">
    <Type Name="book_BooksViewed">
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ViewTimes" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastViewDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BooksViewed" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="book_BookInfo_book_BooksViewed" Member="book_BookInfo" ThisKey="BookId" OtherKey="BookId" Type="book_BookInfo" IsForeignKey="true" />
      <Association Name="aspnet_Users_book_BooksViewed" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
</Database>